export const ADD_STOP_TYPES = {
    UPDATE_LOCATION_NAME: 'UPDATE_LOCATION_NAME',
    UPDATE_PASSENGERS: 'UPDATE_PASSENGERS',
    UPDATE_POSTAL_CODE: 'UPDATE_POSTAL_CODE',
    UPDATE_PICKUP_TIME: 'UPDATE_PICKUP_TIME',
    UPDATE_REMARK: 'UPDATE_REMARK',
    CLEAR_INPUTS: 'CLEAR_INPUTS'
}